# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, nixpkgs, pkgs, modulesPath, ... }:

{
  	imports =
    		[ (modulesPath + "/installer/scan/not-detected.nix")
    		];

  	boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "usb_storage" "sd_mod" ];
  	boot.initrd.kernelModules = [ ];
  	boot.kernelModules = [ "kvm-amd" ];
	boot.extraModulePackages = [ ];

  	fileSystems."/" =
  	{ 
		device = "/dev/disk/by-uuid/5da38907-5c68-4512-9d22-2d993fd11027";
      		fsType = "ext4";
    	};

  	fileSystems."/boot" =
    	{ 		
		device = "/dev/disk/by-uuid/7122-C94F";
      		fsType = "vfat";
    	};

  	fileSystems."/home" =
    	{ 
		device = "/dev/disk/by-uuid/4ec13c0e-c45c-4afd-9c78-4f68e0ee22c4";
		fsType = "ext4";
	};
	
 	 swapDevices = [ ];

 	 # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
 	 # (the default) this is the recommended approach. When using systemd-networkd it's
 	 # still possible to use this option, but it's recommended to use it in conjunction
 	 # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
 	 networking.useDHCP = lib.mkDefault true;
 	 # networking.interfaces.wlp1s0.useDHCP = lib.mkDefault true;

 	 nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
 	 hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
